'use strict';
var assert = require('assert');
var fs = require('fs');
var vm = require('vm');
var modulePath = process.env.STACKLINE_TEST_PACKAGE || require('path').resolve(__dirname, '..');
var path = require(modulePath);
assert.strictEqual(path.resolve('/alpha/beta', '../gamma'), '/alpha/gamma');
assert.strictEqual(path.normalize('/alpha//beta/../gamma/'), '/alpha/gamma/');
assert.strictEqual(path.join('/alpha', 'beta', '..', 'gamma'), '/alpha/gamma');
assert.strictEqual(path.relative('/alpha/beta', '/alpha/gamma/item'), '../gamma/item');
assert.strictEqual(path.basename('/alpha/report.txt', '.txt'), 'report');
assert.strictEqual(path.dirname('/alpha/report.txt'), '/alpha');
assert.strictEqual(path.extname('/alpha/report.txt'), '.txt');
assert.strictEqual(path.isAbsolute('/alpha'), true);
assert.strictEqual(path.isAbsolute('C:\\alpha'), false);
assert.strictEqual(path.sep, '/');
assert.strictEqual(path.delimiter, ':');
assert.strictEqual(path.win32, null);
assert.strictEqual(path.posix, path);
assert.deepEqual(path.parse('/alpha/report.txt'), {root:'/',dir:'/alpha',base:'report.txt',ext:'.txt',name:'report'});
assert.strictEqual(path.format({dir:'/alpha',name:'report',ext:'.txt'}), '/alpha/report.txt');
assert.throws(function () { path.join('/alpha', null); }, TypeError);
var context = {module:{exports:{}},exports:{},process:{cwd:function(){return '/browser-root';}}};
vm.runInNewContext(fs.readFileSync(require('path').join(modulePath,'index.js'),'utf8'), context);
assert.strictEqual(context.module.exports.resolve('child'), '/browser-root/child');
assert.strictEqual(context.module.exports.relative('/browser-root','/browser-root/child'),'child');
console.log('Packed POSIX path API, browser process shim and legacy runtime contracts passed.');
